[package]
name = "loan-amortization"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3

[dependencies]
rust_decimal = { version = "1.29.1", features = ["maths"] }
serde = { version = "1.0", features = ["derive"] }
csv = "1.2.1"
