[package]
name = "loan-amortization"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3

[dependencies]
rust_decimal = { version = "1.29.1", features = ["maths"] }
rust_decimal_macros = "1.29.1"
